version: "3"

services:
  docs:
    image: nginx
    volumes:
      - ./build/html:/usr/share/nginx/html
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.services.${PLATFORM_STACK_NAME}-documentation.loadbalancer.server.port=80
      - traefik.http.routers.${PLATFORM_STACK_NAME}-documentation.rule=Host(`${DOMAIN}`) && PathPrefix(`/docs`)
      - traefik.http.routers.${PLATFORM_STACK_NAME}-documentation.middlewares=documentation-stripprefix
      - traefik.http.middlewares.documentation-stripprefix.stripprefix.prefixes=/docs
  
networks:
  traefik-public:
    external: true